// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModeloCapas.CapaDatos;

#nullable disable

namespace Presentacion.Migrations
{
    [DbContext(typeof(ModeloCapasDbContext))]
    partial class ModeloCapasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Presentacion.CapaDatos.Entidades.MatriculaEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("Anio_Matricula")
                        .HasColumnType("date");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("VehiculoEntityId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("VehiculoEntityId");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("Presentacion.CapaDatos.Entidades.VehiculoEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Cilandraje")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha_Fabricacion")
                        .HasColumnType("date");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Presentacion.CapaDatos.Entidades.MatriculaEntity", b =>
                {
                    b.HasOne("Presentacion.CapaDatos.Entidades.VehiculoEntity", "VehiculoEntity")
                        .WithMany()
                        .HasForeignKey("VehiculoEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehiculoEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
